mysql_aws:
 host: "mulesoft.xxxx.us-east-1.rds.amazonaws.com"
 port: "3306"
 dbase: "mulesoft"
 user: "admin"
 password: "mulesoftxxxxx"
 
mysql_local:
 host: "localhost"
 port: "3306"
 dbase: "mulesoft"
 user: "root"
 password: "xxxxxx"